---
- name: Build docker-compose service folder if needed
  file:
    path: ".build/{{ inventory_hostname }}/{{ item }}"
    state: directory
  delegate_to: localhost
  with_items:
    - "{{ docker_services }}"
#
- name: Build docker-compose service files
  template:
    src: "docker_services/{{ item }}/docker-compose.yml.j2"
    dest: ".build/{{ inventory_hostname }}/{{ item }}/docker-compose.yml"
  delegate_to: localhost
  with_items:
    - "{{ docker_services }}"

- name: Deploy docker-compose files to host
  copy:
    local_follow: yes
    src: ".build/{{ inventory_hostname }}/{{ item }}"
    dest: "/root/ansible_generated_docker-compose/"
    # backup: yes
    mode: '0700'
    owner: root
    group: root
  become: yes
  with_items:
    - "{{ docker_services }}"

- name: Deploy services on host
  docker_service:
    # project_src: ".build/{{ inventory_hostname }}/{{ item }}/docker-compose.yml"
    project_src: "/root/ansible_generated_docker-compose/{{ item }}"
    state: present
    recreate: "{{ docker_service_recreate | default('smart') }}"
  become: yes
  with_items:
    - "{{ docker_services }}"
# vim:ft=ansible:
